#!/usr/bin/env php
<?php

define('TESTBENCH_WORKING_PATH', $workingPath = getcwd());

require isset($_composer_autoload_path) ? $_composer_autoload_path : __DIR__.'/vendor/autoload.php';

$config = Orchestra\Testbench\Foundation\Config::loadFromYaml(
    /*workingPath: */$workingPath,
    /*$filename = */'testbench.yaml',
    /*defaults: */[
        'providers' => [],
        'dont-discover' => [],
    ]
);

$commander = new Orchestra\Testbench\Console\Commander($config, $workingPath);

$commander->handle();
